save:        true
lsi:         false
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     "2"

exclude: [README.md]
